# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78247cd178a15abd38c3bacdc5bbd458060ee0ed4e48987607c3d4016779504b9cbc979b83b9ed2159aeae0dcf194a00b1491914d198105bd2111f278df6322e

test:
  secret_key_base: 1bfcb75ea069412e87d0c02ccbc74b81368fc880c35396a7ae53b23276668cbc51d08c0d95d400ee6f37f0eda45fdb79df91d177eebcf7b5cde0d285bad4911d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
